drain/logging_splunk.go
drain/logging_splunk_test.go
sink/splunk_sink_test.go
testing/mocks.go

instead of master.
modified:   drain/logging_splunk.go
modified:   drain/logging_splunk_test.go
modified:   sink/splunk_sink_test.go
modified:   testing/mocks.go

Fix race condition errors reported by go test -race. Merge to develop

---

drain/logging_splunk.go
drain/logging_splunk_test.go
main.go

Updated drain/logging_splunk to make consumer queue size and hec batch size configurable

Feature/issue26 configurable consumer queue size and HEC batch size

---

tile/tile.yml

Splunk Enterprise < 6.4 does not support the `fields` object on an event sent to it. The standalone nozzle solves this by exposing the `SPLUNK_VERSION` environment variable, and branching based on the version. 
This PR adds a field to the Splunk Config page of the tile configuration options to specify it, with a default value set to `6.6`, which is the default currently set in the nozzle.

Added a field to expose the `SPLUNK_VERSION` nozzle option

---

eventsink/splunk_test.go

While starting development on the nozzle, I found that the `ginkgo -r` test suite will fail with typecheck errors due to a couple of unused variables.  Seems like `applicationIdHex` and `requestIdHex` were added for reference, but not needed to test the envelope.  This commit removes the unused variables.

Removes unused hex ids to fix ginkgo typecheck failures.

---

eventsink/splunk_test.go

Merging changes from PR-146 to develop. 
Thanks to @lancefrench @jghiloni @cholick

Removes unused hex ids to fix ginkgo typecheck failures from PR-146

---

events/events.go

There seems to be a circumstance where logs can end up unindexed in Splunk because they are missing application metadata fields.  This pull requests adds logging for errors returned from  `appCache.GetApp` so that we can see if failed cloud controller calls are the culprit.

Adds a logger to report errors bubbled up from annotation.

---

cache/boltdb.go
tile/tile-history.yml
tile/tile.yml

- Updates tile to support PAS 2.4 - updated xenial stemcell.
- added memory as a config param in the Tile
- added logger to report error when unable to fetch cache copy from remote

Tile update for PAS 2.4

---

cache/boltdb.go
cache/cache.go
cache/cache_test.go
main.go
splunknozzle/config.go
splunknozzle/nozzle.go
testing/app_client_mock.go

Supersedes #148
Currently, `go-cfclient` uses `inline-relations-depth=2`. This is
incredibly inefficient and computationally intensive on the Cloud
Controller database. This commit refactors the caching system to
use `inline-relations-depth=0` and explicitly gets the org and
space for an app to be cached. The TTL for orgs and spaces is
a different value because it can (and should be) much longer than
for apps.
All unit tests currently pass and have added extra tests to ensure
things are working as expected. I did performance testing by creating
a CF environment where I had 1400 apps evenly distributed
(7 apps per space, 8 spaces per org, 25 orgs). Using the new method
of getting orgs and spaces directly resulted in an approximately
25% performance increase, just in terms of speed. This is …

Refactor org/space/app caching

---

eventsink/splunk.go

This will increase the time between connection events to allow an HEC
to catch up. For an example on how this will affect time between connect
attempts, try https://play.golang.org/p/GwqQydwnaFd. You can change the
value of `maxRetries` to see what the *n*th retry attempt will look like
Replaces #149

Convert from static to exponential backoff

---

.circleci/config.yml
events/events.go

- fix null index issue and populate "info_splunk_index" field only when "SPLUNK_INDEX" is configured in applications to route data to different indexes. 
- Update CI deploy pipeline filter

fix info_splunk_index null value issue

---

eventsink/splunk.go

Include the current retry counter (i) in the error message to know how many retries were needed to deliver a batch

INGEST-17577-added retry counter (i) in the error message

---

events/events.go
splunknozzle/config.go
splunknozzle/nozzle.go

Tag fields needs to be revisited in the next release. Not in scope for current release.

remove tag fields - not in scope for 2.0 release.

---

eventwriter/splunk.go
eventwriter/splunk_test.go

Add telemetry data to nozzle hec client.

Add telemetry data (appname and appversion) to HEC requests

---

tile/tile.yml

Updated add-app-info config to be optional in the tile.

make add-app-info an optional field

---

events/events.go
events/events_test.go

The Loggregator ValueMetric evenlopes include double values like NaN or Infinity which require special handling when serializing them.
Currently, the encoder errors out when these special values are sent since they are not included in the JSON spec. This PR attempts to resolve that by converting them to strings NaN, Infinity, -Infinity.

Convert NaN or Infinity value metrics to string

---

splunknozzle/config.go

Made these changes at the config parsing level

Trimmed white space for ApiEndPoint and SplunkHost

---

cache/boltdb.go
cache/cache_test.go
events/events.go

Did following changes:
- Changed the logic of cache.GetApp to retrieve app info from boltdb database if we do not  find it from in-memory cache or remote.
- Updated code comments accordingly
- Added new debug logs to track when cache invalidation is done
- Fixed gostaticcheck warning in some error messages

Updated cache.GetApp logic to retrieve app info from boltdb database as well

---

eventwriter/splunk.go

The HEC connections were not getting reused, and a new connection was getting created at every request. This created issues with the load-balancer in cloud deployment.
The connection logic was already implemented in a way to reuse the connection but the buffer was not drained for the successful requests, which prevented the connections to be reused. Fixed the issue.

drained the response buffer to reuse the connection with HEC

---

eventwriter/splunk.go

If `io.Copy(ioutil.Discard, resp.Body)` returns an error in `eventwriter.send()`, log the error.

Expand error logging

---

README.md
eventsink/splunk.go
eventsink/splunk_test.go
utils/utils.go
utils/utils_test.go

This is to fix an issue, where events with micro/nano second timestamps were not sorted properly due to timestamps getting truncated up to milliseconds.

Nanoseconds in timestamp

---

eventrouter/default.go

While moving routing logic(#313) to Splunk sink writer, one bug was introduced. Due to that, the `events` config wasn't working as expected. 
This PR will fix that issue.

Fix event-type filtration bug

---

.github/update_manifest.sh
.github/workflows/main.yml

While pushing the nozzle to cf, we're using $SPLUNK_METRIC_INDEX env variable, but we're not setting that variable in the first place. So there's a test case failing

Add metric index to main.yml

---

eventwriter/splunk_test.go
monitoring/metric.go
monitoring/metric_test.go
testing/event_writer_metric_mock.go
testing/integration/testcases/test_nozzle_configurations.py

Race conditions detected with `race` flag enabled.
- The ticker field is initialised in a goroutine and stopped in main thread. Add a mutex to access this field

Fix race conditions and fix some unit test cases

---

.semgrepignore

We don't need to check for vendor/* for semgrep, 
those are libraries.

fix: add vendor to semgrepignore

---

README.md
eventrouter/default.go
eventsink/splunk.go
eventwriter/splunk_event.go
splunknozzle/config.go
splunknozzle/nozzle.go

Added some config options for keep alive timeout.
Timeout is now configurable with KEEP_ALIVE_TIMER, and REFRESH_SPLUNK_CONNECTION can be used to turn it on/off.

Keepalive timeout config

---

.github/tile-builder.sh

Updated tile builder to fix this issue:
https://github.com/cloudfoundry-community/splunk-firehose-nozzle/issues/362

Tile builder up

---

.github/pre-req.sh
.github/update_manifest.sh
.github/workflows/main.yml

Automatisation of creating ISV environment for pcf tests.

chore: setup pcf

---

.github/workflows/main.yml
README.md
eventsink/splunk.go
splunknozzle/config.go
splunknozzle/config_test.go
testing/integration/testcases/test_nozzle_configurations.py
testing/integration/testcases/test_nozzle_configurations_local.py
tile/tile.yml

Reviewing the descriptions of variables in UI.

docs: update variable description
