auth/token_fetcher_test.go
drain/logging_splunk.go
drain/logging_splunk_test.go
main.go
sink/splunk_sink.go
sink/splunk_sink_test.go
splunk/splunk_client_test.go

Change package to match new org

---

drain/logging_splunk.go
drain/logging_splunk_test.go
sink/splunk_sink_test.go
testing/mocks.go

modified:   drain/logging_splunk.go
modified:   drain/logging_splunk_test.go
modified:   sink/splunk_sink_test.go
modified:   testing/mocks.go

Fix race condition errors reported by go test -race

---

firehoseclient/firehoseclient.go
firehoseclient/firehoseclient_suite_test.go
firehoseclient/firehoseclient_test.go
main.go
nozzle/nozzle.go
testing/event_router_mock.go
testing/firehose_consumer_mock.go

modified:   firehoseclient/firehoseclient.go
new file:   firehoseclient/firehoseclient_suite_test.go
new file:   firehoseclient/firehoseclient_test.go
modified:   main.go
new file:   nozzle/nozzle.go
new file:   testing/event_router_mock.go
new file:   testing/firehose_consumer_mock.go

Issue 28. Make firehoseclient testable and add unit test

---

Makefile
firehoseclient/firehoseclient.go

Fix one warning reported by "go vet" in firehoseclient.go which is
unreachable line of code
modified:   Makefile
modified:   firehoseclient/firehoseclient.go

Enhance makefile for code coverage and add testall for all testing

---

.gitignore
Makefile
main.go

is busy, it may come back to client in 25 seconds
modified:   Makefile
modified:   main.go

Bump up the default timeout value for keepalive since when logaggrator

---

main.go

Revert keepalive interval from 120s to 25s. Seems firehose doesn't like

---

drain/logging_splunk.go
drain/logging_splunk_test.go

modified:   drain/logging_splunk.go
modified:   drain/logging_splunk_test.go

JSON message parsing

---

README.md

Clean up and enrich README markdown

---

.gitignore
README.md
scripts/dump_app_info.go

modified:   .gitignore
new file:   scripts/dump_app_info.go

Tool of dumping app info to boltdb

---

caching/caching_boltdb.go
caching/caching_test.go
nozzle/config.go
nozzle/nozzle.go

modified:   caching/caching_boltdb.go
modified:   caching/caching_test.go
modified:   nozzle/config.go
modified:   nozzle/nozzle.go

Add missing app cache invalidation support

---

README.md

Fixed some spelling and ordering in Readme.

Rearranged Readme and fixed some spelling

---

README.md
eventsink/splunk.go
splunknozzle/config.go
splunknozzle/config_test.go
splunknozzle/nozzle.go

Code, Tests and Readme added for TraceLogging

Issue 80 add subscription-id and trace-logging flag

---

README.md

@Dontre-Splunk - Here are the edits to the added README configurations. Just made some adjustments for passive-active voice & clarity.

README edits from doc team

---

tile/tile.yml

Update Skip_SSL_Validation and Additional Fields description

update fields description

---

.gitignore
tools/data_gen/data_gen.go

Merge to master to include latest tile changes

Merge to master to include latest tile changes

---

README.md

Merge latest Tile related changes to master

Merge latest Tile related changes to master

---

eventsink/splunk_test.go

Reverts cloudfoundry-community/splunk-firehose-nozzle#146
Will move this to develop branch.

Revert "Removes unused hex ids to fix ginkgo typecheck failures."

---

.circleci/ci_nozzle_manifest.yml
.circleci/config.yml
.circleci/pre-req.sh
.circleci/update_manifest.sh
README.md

Added CircleCI (CI) pipelines:
- build
- test
- deploy

Added CircleCI (CI) pipelines

---

.circleci/ci_nozzle_manifest.yml
.circleci/config.yml
.circleci/push_tile.sh
.circleci/tile-builder.sh
.circleci/update_manifest.sh
.gitignore

Updated CI pipelines to include deploy nozzle, tile builder and push tile to internal bucket CI steps.

Added deploy and push CI pipelines

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/enhancement_request.md

Add issue and enhancement request templates

Add issue and enhancement request templates

---

events/events.go
glide.lock

Added back sirupsen  in lowercase

Update glide lock 

---

.circleci/pre-req.sh
README.md
splunknozzle/config.go
splunknozzle/config_test.go
tile/tile.yml

Remove splunk version from Tile

Remove splunk version field from Tile

---

README.md
manifest.yml.template

updated readme and manifest template

Updated readme for 1.1 release

---

nozzle/nozzle.go
tile/tile.yml

Added Firehose-keep-alive config param to the tile and updated org-space-cache-invalidate-ttl default value in the tile.

Updated tile

---

README.md
ci/nozzle_manifest.yml

Updated readme and nozzle manifest with client credentials.

update readme and nozzle manifest with client creds

---

.circleci/ci_nozzle_manifest.yml
.circleci/data_gen_manifest.yml

lower nozzle memory and instance count
lower datagen eps and instance count

lower resource usage for ci env

---

.circleci/ci_nozzle_manifest.yml

updated ci config for func tests

updated ci config for func tests

---

events/events.go

Add tags data from CF deployments

Add tags data from CF deployments

---

glide.lock
vendor/code.cloudfoundry.org/go-loggregator/v8/rlp_gateway_client.go
vendor/code.cloudfoundry.org/go-loggregator/v8/rlp_gateway_client_test.go

Updated go-loggregator library

update client lib to include perf related fix

---

eventrouter/default.go
events/events.go
events/events_test.go
splunknozzle/config.go
splunknozzle/nozzle.go

Added config option to filter on app metadata fields. (Defaults: true)

Metadata config filter

---

eventrouter/eventrouter_test.go
events/events.go
events/events_test.go
splunknozzle/config.go
splunknozzle/nozzle.go
testing/integration/testcases/test_nozzle_configurations.py

Adding app-name to metadata filter

add add-app-name field to metadata filter

---

tile/tile.yml

upate app-info config param in the tile

upate app-info config param in the tile

---

.circleci/ci_nozzle_manifest.yml
README.md

update config per new params and versions

update config per new params and versions

---

events/events.go
eventsink/splunk.go
eventwriter/splunk.go
eventwriter/splunk_test.go

- Add HEC retry counter 
- Fix null index value issue
- Added HEC-telemetry headers - appName, appVersion.

updates for v1.2.0 release

---

.circleci/ci_nozzle_manifest.yml
eventrouter/default.go
eventrouter/eventrouter_test.go
events/events.go
events/events_test.go
splunknozzle/config.go
splunknozzle/config_test.go
splunknozzle/nozzle.go
splunknozzle/nozzle_test.go

Update add-app-info to be a configurable list of app metadata fields. (AppName, OrgName/Guid, SpaceName/Guid
Remove cf_origin and cf_ignored_app fields from metadata info.

Metadata filter 1.2.0

---

.circleci/config.yml
eventrouter/eventrouter_test.go
events/events.go
events/events_test.go

Fixed disable app logging filter

enable ignore app config

---

.circleci/config.yml
.circleci/pre-req.sh
eventwriter/splunk.go
eventwriter/splunk_test.go

- updated version
- update ci config

Update hec telemetry 

---

eventwriter/splunk.go
eventwriter/splunk_test.go
splunknozzle/nozzle.go

Used the version set by environment variable at the build time

replaced hard-coded nozzle version

---

splunknozzle/config.go
splunknozzle/config_test.go
splunknozzle/nozzle_test.go

- Removed unused params: job_index and job_name

removed job_name and job_index

---

README.md

Added more details regarding how app cache works with an example

App cache docs

---

.github/workflows/main.yml

We can then download this tile and submit it to VMware

chore: extract tile as artifact from workflow

---

README.md

Short documentation for running pcf with EP instance

Edge processor configuration

---

README.md
dashboards/dashboard.xml

Pcf dashboard

---

README.md

Updated tas info about compability

Updated tas info

---

mkdocs.yml
scripts/ci_nozzle_manifest.yml
sonar-project.properties
tile/tile.yml

Resolving issues from sonarqube.

chore: clear sonarqube issues
